name: BuildPckTest
on:
  push:
    branches:
      - master
    paths:
      - setup.py

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9, 3.10, 3.11 ]


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run:
          python -m pip install --upgrade pip
          python setup.py bdist_wheel

